name: CINCO
favicon: null
layout_spectrum: 0.5886770682409406
typography_spectrum: 0.9230708272662014
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.3342600183095783
  lightness: 0.17269782815128565
  saturation: 0.542745930608362
  rhythmicContrast: 0.5337618116755038
purpose: []
